config/routes.rb
Rails.application.routes.draw do
  resources :reviews, except: [:destroy, :edit, :update,:show]
  resources :gigs
  resources :clubs, except: [:destroy]
  resources :jokes
  resources :users
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "users#index"

  delete '/sessions/page_reset', to: 'sessions#page_reset', as: 'page_reset'
  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'

  patch "/jokes/:id/like", to: "jokes#like", as: "like"
  patch "/jokes/:id/dislike", to: "jokes#dislike", as: "dislike"
  


  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :reviews
    has_many :gigs
    has_many :users, through: :gigs


    def upcoming_gigs
        self.gigs.sort_by {|gig| gig.date}
    end

end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :club
  belongs_to :user
  validate :gig_available
  validates :price, :club, :user, :date, presence: true 
  validates :price, numericality: {greater_than: 0, less_than_or_equal_to: 30}

  def gig_available
    if self.user.featured_jokes == nil
      self.errors.add(:user_id, "Comedian Needs Jokes to Get a Gig")
    elsif self.user.dogshit_joke.dislike > 30
      self.errors.add(:user_id, "Get the F Outta Here with that Trash🖕")
    elsif self.user.featured_jokes.like < self.club.req_likes
      self.errors.add(:user_id, "Not Funny Enough for This Club")
    end
  end

end

app/models/joke.rb
class Joke < ApplicationRecord
  belongs_to :user
  validates :content, :user_id, presence: true

  
  # def sorted_jokes
  #   self.sort_by {|joke|joke.like}.reverse
  # end
  
  # <%@sorted_jokes = @jokes.sort_by {|joke|joke.like}.reverse %>
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :club
  validates :rating, numericality: {greater_than: 0, less_than_or_equal_to: 5}
  validates :rating, :date, :club, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :jokes, dependent: :destroy
    has_many :gigs, dependent: :destroy
    has_many :clubs, through: :gigs
    validates :name, :age, :user_name, :email, :hometown, presence: true 


    has_secure_password

    def featured_jokes
        test = self.jokes.max_by {|joke| joke.like}
    end

    def upcoming_gigs
        self.gigs.sort_by {|gig| gig.date}
    end

    def dogshit_joke
        test = self.jokes.max_by {|joke| joke.dislike}
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :logged_in_user
    before_action :authorization
    
    def logged_in_user 
        @current_user = User.find_by(id: session[:user_id])
    end 

    def authorization 
        redirect_to users_path unless logged_in_user
    end 
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    def index 
        @clubs = Club.all
    end 
    
    def show
        @club = Club.find(params[:id])
        @review = Review.new
    end 
    
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController

    def index 
        @gigs = Gig.all
    end 

    def new
        @gig = Gig.new
    end

    def create
        # byebug
        # if session[:user_id].featured_jokes.likes >= @gig.club.req_likes
        @user = session[:user_id]
        @gig = Gig.create(gig_params)
        if @gig.valid?
            redirect_to club_path(@gig.club)
        else
            flash[:gig_errors] = @gig.errors.full_messages
            redirect_back fallback_location: user_path(@user)
        end
    end

    def show
        @gig = Gig.find(params[:id])
    end

    def destroy
        @user = session[:user_id]
        @gig = Gig.find(params[:id])
        @gig.destroy
        redirect_to user_path(@user)
    end
    
    private
    def gig_params
        params.require(:gig).permit(:club_id, :user_id, :date, :price)
    end
    

end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController

    def index 
        @jokes = Joke.all
    end 

    def new
        @joke = Joke.new
    end

    def create
        @user = session[:user_id]
        @joke = Joke.create(joke_params)
        if @joke.valid?
            redirect_to user_path(@joke.user)
        else 
            flash[:joke_errors] = @joke.errors.full_messages
            redirect_to user_path(@user)
        end
    end
    
    def show
        @sorted_jokes = Joke.sorted_jokes
        @joke = Joke.find(params[:id])
    end
    
    def edit
        @joke = Joke.find(params[:id])
    end
    
    def update
        @joke = Joke.find(params[:id])
        @joke.update(joke_params)
        redirect_to user_path(@joke.user)
    end
    
    def like 
        @joke = Joke.find(params[:id])
        @joke.like += 1
        @joke.save
        redirect_back fallback_location: jokes_path
    end
    
    def dislike 
        @joke = Joke.find(params[:id])
        @joke.dislike += 1
        @joke.save
        redirect_back fallback_location: jokes_path
    end
    
    private
    
    def joke_params
        params.require(:joke).permit(:user_id, :like, :dislike, :content)
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index 
        @reviews = Review.all
    end 
    
    def new
        @review = Review.new
    end

    def create
        @review = Review.create(review_params)
        # if session[:user_id] == @user.id 
        if @review.valid?
            redirect_to club_path(@review.club)
        else 
            flash[:my_errors] = @review.errors.full_messages
            redirect_to new_review_path
        end
    end

    def show
        @review = Review.find(params[:id])
    end

    


    private

    def review_params
        params.require(:review).permit(:club_id, :rating, :date, :content)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :authorization, only: [:new, :create]

    def logout 
        session.delete(:user_id)
        redirect_to users_path
    end 

    def new
    end 

    def create 
        user = User.find_by(user_name: params[:session][:user_name])
     
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        # elsif user.invalid?
        #     falsh[:error] = "User does not exist"
        #     redirect_to new_login_path
        else
            flash[:error] = "Username or Password was Incorrect"
            redirect_to new_login_path
        end 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorization, only: [:new, :create, :index]
    def index 
        @users = User.all
    end 
    
    def show
        @user = User.find(params[:id])
        @gig = Gig.new
        @joke = Joke.new
    end 

    
    def new
        @user = User.new
    end
    
    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            flash[:my_errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end
    
    def edit
        @user = User.find(params[:id])

    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
          else
            flash[:my_errors] = @user.errors.full_messages
            redirect_to edit_user_path
        end
        
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(:user_name, :name, :email, :pic, :bio, :age, :password, :hometown)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/index.html.erb
<body>
<h1 style="text-align:center">Clubs</h1>



 <div class="container">
    <% @clubs.each do |club| %>
    <div class="tile">
        <p class="profile-pic"> <%= link_to(image_tag(club.pic), club_path(club)) %></p>
        <%= link_to club.name, club_path(club) %>
        
        </div>
    <% end %>
 </div>

</body>

app/views/clubs/show.html.erb
<body>
<div class="club_show">
    <div class="div1_club"> 
        <h1 style="text-align:center"><%= @club.name %></h1>
        <div style="text-align:center"><b>Address: </b><%= @club.address %></div>
        <div style="text-align:center"><b>Description: </b><%= @club.description %></div><br>
        <div class="show-pic" style="text-align:center"> <img  src=<%= @club.pic%> height="500"></div>
    </div>

    <div class="div2_club"> 
        <h4 style="text-align:center">Reviews </h4>
        <% @club.reviews.each do |review| %>
            <div style="text-align:center"><b>Rating : </b> <%= review.rating %> star</div>
            <div style="text-align:center"><b>Content :</b><%= review.content %></div>
            <div style="text-align:center"><b>Date :</b> <%= review.date.strftime ('%B %-d, %Y') %></div>
        <% end %>
    <h4 style="text-align:center"> Write a Review <%= render partial: "reviews/form" %></h4>
    
    <h4 style="text-align:center">Upcoming Performances</h4>
    
        <% @club.upcoming_gigs.each do |gig| %>
            <div style="text-align:center"><b>Performing : </b> <%= gig.user.name %></div>
            <div style="text-align:center"><b>Price : $</b> <%= gig.price %></div>
            <div style="text-align:center"><b>Date : </b> <%= gig.date.strftime ('%B %-d, %Y') %></div>
            <br>

        <% end %>
    </div>


    <div class="div3_club"style="text-align:center"> <iframe width="300" height="300" src="https://www.youtube.com/embed/QkqEf78xL-U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div>
    <div class="div4_club"style="text-align:center"> <iframe src="https://giphy.com/embed/EDV30lQQ9VW5q" width="300" height="300" frameBorder="0" class="giphy-embed" ></iframe></div>



</body>

</div>

app/views/gigs/_form.html.erb
<body>
<% if flash[:gig_errors] %>
    <% flash[:gig_errors].each do |error| %>
        <div style="color: red"><%= error %></div>
    <% end %>
<% end %>

<%= form_for(@gig) do |f| %>
    <%= f.label :club %>
    <%= f.collection_select :club_id, Club.all, :id, :name %>

    <%= f.hidden_field :user_id, value: session[:user_id] %>

    <%= f.label :date %>
    <%= f.date_field :date %>

    <%= f.label :price %>
    <%= f.number_field :price %>
    
    <%= f.submit "Book A Gig" %>
<% end %>

</body>

app/views/gigs/new.html.erb
<body>
<h1 style="text-align: center"> New Gig Form</h1>

<%= render "form" %>
</body>

app/views/gigs/show.html.erb
<body>
<h1 style="text-align: center"> <%= @gig.user.name %>'s Upcoming Gigs : </h1>

<br>

<h2 style="text-align: center"> <%= @gig.club.name %> </h2>

<h3 style="text-align: center">Price : $ <%= @gig.price %> </h3>

</body>

app/views/jokes/_form.html.erb
<body>
<% if flash[:joke_errors] %>
    <% flash[:joke_errors].each do |error| %>
        <div style="color: red"><%= error %></div>
    <% end %>
<% end %>



<%= form_for(@joke) do |f| %>
    <%= f.hidden_field :user_id, value: session[:user_id] %>
    <%= f.hidden_field :like, value: 0 %>
    <%= f.hidden_field :dislike, value: 0 %>
    <%= f.label "Content" %>
    <%= f.text_field :content %>
    <%= f.submit %>
<% end %>

</body>

app/views/jokes/index.html.erb
<body>
<div class="joke_index">
    <div class="div1_joke"><h1> Newest Jokes </h1>
        <%@sorted_jokes = @jokes.sort_by {|joke|joke.created_at}.reverse %>
        <% @sorted_jokes.each do |joke| %>
        <div class="container">
            <div><%= joke.content %>  - <%= link_to joke.user.name, user_path(joke.user) %>  <b>Likes: </b><%= joke.like %> <b>Dislikes: </b><%= joke.dislike %></div>
            <div><%= button_to "👍", like_path(joke), method: :patch %></div>
            <div><%= button_to "👎", dislike_path(joke), method: :patch %></div>
        </div>
        <br>
        <% end %> 
    </div>

    <div class="div2_joke"><h1> Most Liked Jokes </h1>
        <%@sorted_jokes = @jokes.sort_by {|joke|joke.like}.reverse %>
        <% @sorted_jokes.each do |joke| %>
        <div class="container">
            <div><%= joke.content %>  - <%= link_to joke.user.name, user_path(joke.user) %>  <b>Likes: </b><%= joke.like %> <b>Dislikes: </b><%= joke.dislike %></div>
            <div><%= button_to "👍", like_path(joke), method: :patch %></div>
            <div><%= button_to "👎", dislike_path(joke), method: :patch %></div>
        </div>
        <br>
        <% end %>
    </div>
</div>
 </body>

app/views/jokes/new.html.erb
<body>
<h1 style="text-align: center"> New Joke Form </h1>


<%= render "form" %>
</body>

app/views/jokes/show.html.erb
<body>
    <h1 style="text-align:center">Author<%= @joke.user.name %></h1>


    <p style="text-align:center"><b>Conte: </b><%= @joke.content %></p>
    <p style="text-align:center"><b>Likes: </b><%= @joke.like %></p>
    <p style="text-align:center"><b>Dislike: </b><%= @joke.dislike %></p>

    <div style="text-align: center"><%= button_to "👍", {:controller => :jokes, :action => :like}, { :method => :patch } %></div>

     <div style="text-align: center"><%= button_to "👎", {:controller => :jokes, :action => :like}, { :method => :patch } %></div>
    
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JokesOnUs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>

  <div class="banner">
      <%= image_tag "joke_banner.jpg", class: "banner-img" %>
    </div>

    <ul class="nav">
      <li><%= link_to "Comedians", users_path %></li>
      <li><%= link_to "Clubs", clubs_path %></li>
      <li><%= link_to "Top Jokes", jokes_path %></li>

      <% if @current_user %>
        <b><li style="color:white;" class="right">Hello <%= link_to @current_user.name, user_path(@current_user) %> </li></b>
        <li class="right"><%= link_to "Log Out", logout_path, method: :delete %></li>
      <% else %>
        <li class="right"><%= link_to "Login", new_login_path %></li>
        <li class="right"><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<body>
<% if flash[:my_errors] %>
    <% flash[:my_errors].each do |error| %>
        <div style="color: red"><%= error %></div>
    <% end %>
<% end %>



<%= form_for(@review) do |f| %>
    <%= f.hidden_field :club_id, value: @club.id %>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    <%= f.label :date %>
    <%= f.date_field :date %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
<% end %>
</body>

app/views/reviews/index.html.erb
<body>
<h1>Reviews</h1>

<ul>
    <% @reviews.each do |review| %>
      
        <li><%= review.club.name %>,  Rating: <%= review.rating %>, Content: <%= review.content%>, Date: <%= review.date.strftime ('%B %-d, %Y') %></li>
        
    <% end %>
 </ul>
 </body>

app/views/reviews/new.html.erb
<body>
<h1 style="text-align: center"> New Review Form</h1>

<%= render "form" %>
</body>

app/views/users/_form.html.erb
<body>
<% if flash[:my_errors] %>
    <% flash[:my_errors].each do |error| %>
        <div style="color: red"><%= error %></div>
        <% end %>
<% end %>

<%= form_for(@user) do |f| %>
    <div  style="text-align: center">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>
    
    <%= f.label :email %>
    <%= f.email_field :email %><br>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :bio %>
    <%= f.text_field :bio %><br>

    <%= f.label :age %>
    <%= f.number_field :age %><br>

    <%= f.label :hometown %>
    <%= f.text_field :hometown %><br>

    <%= f.label "Profile Picture URL" %>
    <%= f.text_field :pic %><br>
    
    <%= f.submit %>
    </div>
<% end %>
</body>

app/views/users/edit.html.erb
<body>
<h1 style="text-align: center"> Edit User Page </h1>


<%= render "form" %>
</body>

app/views/users/index.html.erb
<body>
<h1 style="text-align: center">Comedians</h1>



<div class="container">

    <% @users.each do |user| %>
        <div class="tile">
        <p class="profile-pic"> <%= link_to(image_tag(user.pic), user_path(user)) %></p><br>
        <p><%= link_to user.name, user_path(user) %></p>
        
        </div>
    <% end %>
 </div>

</body>

app/views/users/new.html.erb
<body>
<h1 style="text-align: center"> New User Page </h1>


<%= render "form" %>
</body>

app/views/users/show.html.erb
<body>
<div class="comedian_show">

    <div class="div1_comedy">
        <h1 style="text-align:center"><%= @user.name %></h1>

            <div style="text-align:center"><b>Email : </b><%= @user.email %></div>
            <div style="text-align:center"><b>Age : </b><%= @user.age %></div>
            <div style="text-align:center"><b>Hometown : </b><%= @user.hometown %></div>
            <div style="text-align:center"><b>Bio : </b><%= @user.bio %></div><br>
            <div class="show-pic" style="text-align:center"> <img  src=<%= @user.pic%> height="500"></div>
    </div>

    <div class="div2_comedy center">

        <% if session[:user_id] == @user.id %>
            <h4 style="text-align:center"><%= link_to 'Edit Profile', edit_user_path(@user) %>
            <h4 style="text-align:center"><%= button_to 'Delete Profile', user_path, method: :delete %>
            <h4 style="text-align:center"> Book A Gig<%= render partial: "gigs/form" %></h4>
        <% end %>

       
        <h4 style="text-align:center"> Upcoming Gigs : </h4>
            <% @user.upcoming_gigs.each do |gig| %>
                <div style="text-align:center"><b><%= gig.club.name %></b> - Date : <%= gig.date.strftime ('%B %-d, %Y') %></div>
                <% if session[:user_id] == @user.id %>
                    <div style="text-align:center"><%= button_to "Delete", gig_path(gig), method: :delete %></div>
                <% end %>
        <% end%>

        <h4 style="text-align:center"> Jokes :</h4>
            <% @user.jokes.each do |joke| %>
            <div class="container">
                <div style="text-align:center"><%= joke.content %> Likes : <%= joke.like%> Dislikes : <%= joke.dislike %></button></div>
                <div><%= button_to "👍", like_path(joke), method: :patch %></div>
                <div><%= button_to "👎", dislike_path(joke), method: :patch %></div>
            </div>
            <% end %>
        </div>

        <div class="div3_comedy">
            <% if session[:user_id] == @user.id %>
            <h4 style="text-align:center"> Create a New Joke <%= render partial: "jokes/form" %></h4>
            <% end %>
        </div>


    <div class="div4_comedy"style="text-align:center"><iframe width="300" height="300" src="https://www.youtube.com/embed/zSWUWPx2VeQ" frameborder="0" allow="accelerometer;loop=1;mute=1; autoplay=1; clipboard-write; encrypted-media; gyroscope; picture-in-picture" ></iframe></div>

    <div class="div5_comedy"style="text-align:center"><iframe src="https://giphy.com/embed/3o7TKQveWJpORTTQpa" width="300" height="300" frameBorder="0" class="giphy-embed"></iframe></div>


</div>
</body>